package middleware

import (
	"net/http"
	"strings"

	"github.com/templui/goilerplate/internal/ctxkeys"
)

// SecurityHeaders adds security-related HTTP headers to all responses
//
// These headers protect against common web vulnerabilities including:
// - Clickjacking attacks (X-Frame-Options)
// - MIME-type sniffing attacks (X-Content-Type-Options)
// - Cross-Site Scripting (Content-Security-Policy)
// - Information leakage (Referrer-Policy)
// - Unwanted feature access (Permissions-Policy)
//
// All headers follow OWASP best practices and modern browser standards.
func SecurityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Get the nonce generated by NonceMiddleware
		// This will be injected into the CSP header to allow specific inline scripts
		nonce := GetNonce(r.Context())
		if nonce == "" {
			// Fallback: use empty nonce (degraded CSP protection)
			// This shouldn't happen if NonceMiddleware is properly configured
			nonce = ""
		}

		// Get config to check for S3 endpoint (for CSP img-src)
		cfg := ctxkeys.Config(r.Context())
		// X-Frame-Options: Prevents clickjacking attacks
		//
		// Clickjacking is when an attacker embeds your site in an invisible iframe
		// on their malicious site, tricking users into clicking on your buttons
		// while thinking they're clicking on the attacker's site.
		//
		// Options:
		//   DENY - Never allow framing (most secure, recommended for most sites)
		//   SAMEORIGIN - Allow framing only from same origin
		//   ALLOW-FROM uri - Allow framing from specific URI (deprecated, not recommended)
		//
		// We use DENY because there's rarely a legitimate reason to embed your
		// app in an iframe. If you need iframe embedding, use SAMEORIGIN or
		// implement CSP frame-ancestors instead.
		w.Header().Set("X-Frame-Options", "DENY")

		// X-Content-Type-Options: Prevents MIME-type sniffing attacks
		//
		// Browsers sometimes try to "guess" the content type of a response
		// (MIME sniffing) even when the server sets a Content-Type header.
		// This can lead to security issues:
		//
		// Example attack:
		//   1. Attacker uploads file "image.jpg" that contains JavaScript
		//   2. Server serves it as image/jpeg
		//   3. Browser sniffs content, detects JavaScript, executes it
		//   4. XSS vulnerability!
		//
		// "nosniff" tells browsers to strictly follow the declared Content-Type
		// and never try to guess. This prevents uploaded files from being
		// executed as scripts.
		w.Header().Set("X-Content-Type-Options", "nosniff")

		// Referrer-Policy: Controls how much referrer information is sent
		//
		// When users click a link from your site to another site, browsers send
		// a "Referer" header containing the URL they came from. This can leak
		// sensitive information like:
		//   - Session IDs in URLs (bad practice but happens)
		//   - Private page URLs (/admin/users/123/edit)
		//   - Search queries (/search?q=sensitive+medical+condition)
		//
		// Options explained:
		//   no-referrer - Never send Referer (most private, might break analytics)
		//   same-origin - Send Referer only to same domain
		//   strict-origin - Send only origin (https://example.com) not full URL
		//   strict-origin-when-cross-origin - Full URL to same-origin, only origin to other sites (RECOMMENDED)
		//
		// We use "strict-origin-when-cross-origin" because it:
		//   - Sends full URL within your app (good for your own analytics)
		//   - Sends only origin to external sites (protects user privacy)
		//   - Downgrades HTTPS→HTTP properly (no referrer sent)
		w.Header().Set("Referrer-Policy", "strict-origin-when-cross-origin")

		// Permissions-Policy: Controls which browser features/APIs can be used
		//
		// Modern browsers expose powerful APIs (camera, microphone, geolocation,
		// payment, etc.). By default, these are available to your site AND to
		// any third-party scripts or iframes you embed.
		//
		// This header explicitly disables features you don't use, preventing:
		//   - Malicious third-party scripts from accessing device hardware
		//   - Embedded iframes from requesting sensitive permissions
		//   - Accidental API usage that increases your attack surface
		//
		// Format: feature=(allowed-origins)
		//   () = disabled for everyone including your site
		//   (self) = enabled only for your origin
		//   (self "https://trusted.com") = enabled for your origin + specific domain
		//
		// We disable features that most SaaS apps don't need. Uncomment/modify
		// if your app needs specific features:
		//   geolocation - GPS location tracking
		//   microphone - Audio recording
		//   camera - Video/photo capture
		//   payment - Payment Request API
		//   usb - USB device access
		//   magnetometer - Device orientation/motion sensors
		w.Header().Set("Permissions-Policy", "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=()")

		// Content-Security-Policy (CSP): The most powerful security header
		//
		// CSP controls what resources (scripts, styles, images, etc.) can be
		// loaded and executed on your page. This is your main defense against
		// Cross-Site Scripting (XSS) attacks.
		//
		// How CSP prevents XSS:
		//   1. Attacker injects: <script>alert('XSS')</script>
		//   2. CSP blocks it because inline scripts without nonce are not allowed
		//   3. Even if attacker injects: <script src="http://evil.com/xss.js">
		//   4. CSP blocks it because only whitelisted domains are allowed
		//
		// CSP Directives explained:
		//
		//   default-src 'self'
		//     Fallback policy for any resource type not explicitly defined.
		//     'self' = allow loading only from same origin (your domain)
		//
		//   script-src 'self' 'nonce-...' cdn.jsdelivr.net cdnjs.cloudflare.com www.googletagmanager.com plausible.io
		//     Controls which JavaScript can execute.
		//     'self' = allow scripts from your domain (/assets/app.js)
		//     'nonce-...' = allow inline <script nonce="..."> with matching nonce
		//     cdn.jsdelivr.net = htmx library (with integrity check for extra security)
		//     cdnjs.cloudflare.com = highlight.js for code syntax highlighting
		//     www.googletagmanager.com = Google Analytics 4 (optional, enable via GOOGLE_ANALYTICS_ID)
		//     plausible.io = Plausible Analytics (optional, enable via PLAUSIBLE_DOMAIN)
		//     We use nonces because templ generates inline scripts for interactivity.
		//     NEVER use 'unsafe-inline' - it defeats the entire purpose of CSP!
		//
		//   style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com
		//     Controls which CSS can be applied.
		//     'self' = allow stylesheets from your domain
		//     'unsafe-inline' = allow inline styles (<style> and style="...")
		//     cdnjs.cloudflare.com = highlight.js themes
		//     We use 'unsafe-inline' because Tailwind and templ generate inline styles.
		//     This is acceptable for CSS (unlike JavaScript) because CSS can't execute code.
		//
		//   img-src 'self' data: https:
		//     Controls which images can be loaded.
		//     'self' = images from your domain
		//     data: = data URLs (data:image/png;base64,...)
		//     https: = any HTTPS image source (for user avatars from S3, etc.)
		//
		//   font-src 'self' data:
		//     Controls which fonts can be loaded.
		//     'self' = fonts from your domain
		//     data: = data URL fonts (some icon fonts use this)
		//
		//   connect-src 'self' *.google-analytics.com analytics.google.com plausible.io
		//     Controls which domains can be contacted via AJAX/fetch/WebSocket.
		//     'self' = only your domain (prevents data exfiltration to attacker's server)
		//     analytics domains = allow Google Analytics (wildcard for regional subdomains) + Plausible to send events
		//
		//   frame-ancestors 'none'
		//     Controls which sites can embed your page in iframe (CSP equivalent of X-Frame-Options).
		//     'none' = never allow embedding (same as X-Frame-Options: DENY)
		//
		//   base-uri 'self'
		//     Controls which URLs can be used in <base> tag.
		//     Prevents attackers from changing base URL to hijack relative links.
		//
		//   form-action 'self'
		//     Controls which URLs forms can submit to.
		//     Prevents attacker from changing form action to send data to their server.
		//
		// Analytics domains are hardcoded (Google Analytics + Plausible)
		// No performance impact if not used - browsers only connect when scripts are loaded
		//
		// Testing CSP:
		//   1. Enable CSP
		//   2. Open browser DevTools → Console
		//   3. Look for CSP violation errors (will show blocked resources)
		//   4. Adjust policy or fix violations
		//   5. Use Content-Security-Policy-Report-Only first to test without blocking

		// Build img-src directive dynamically with S3 endpoint if configured
		// This allows loading images from S3-compatible storage (MinIO, AWS S3, CloudFlare R2, DO Spaces, etc.)
		imgSrc := "img-src 'self' data: https:"
		if cfg != nil && cfg.S3Endpoint != "" {
			// Add S3 endpoint to whitelist (e.g., http://localhost:9000 for MinIO dev)
			imgSrc += " " + cfg.S3Endpoint
		}

		// Umami host (default cloud.umami.is, configurable for self-hosted)
		// Cloud requires multiple gateway domains, self-hosted only needs the single host
		umamiHost := "cloud.umami.is"
		umamiCsp := "https://cloud.umami.is https://analytics.umami.is https://gateway.umami.is https://eu.umami.is https://api-gateway-eu.umami.dev https://api-gateway.umami.dev"

		if cfg != nil && cfg.UmamiHost != "" && cfg.UmamiHost != "cloud.umami.is" {
			umamiHost = cfg.UmamiHost
			umamiCsp = "https://" + cfg.UmamiHost
		}

		// Plausible host (default plausible.io, configurable for self-hosted)
		plausibleHost := "plausible.io"
		if cfg != nil && cfg.PlausibleHost != "" {
			plausibleHost = cfg.PlausibleHost
		}

		// Build CSP policy with real nonce value
		cspPolicy := strings.Join([]string{
			"default-src 'self'",
			"script-src 'self' 'nonce-" + nonce + "' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://" + umamiHost + " https://" + plausibleHost + " https://www.googletagmanager.com",
			"style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com",
			imgSrc, // Dynamic img-src with S3 endpoint
			"font-src 'self' data:",
			"connect-src 'self' " + umamiCsp + " https://" + plausibleHost + " https://*.google-analytics.com https://analytics.google.com",
			"frame-ancestors 'none'",
			"base-uri 'self'",
			"form-action 'self' https://sandbox.polar.sh https://polar.sh https://checkout.stripe.com",
		}, "; ")

		w.Header().Set("Content-Security-Policy", cspPolicy)

		next.ServeHTTP(w, r)
	})
}
